import { NextResponse } from "next/server";
import { createServerClient } from "@supabase/ssr";
import type { NextRequest } from "next/server";

/**
 * V6 authentication boundary.
 *
 * IMPORTANT: middleware is intentionally responsible ONLY for authentication.
 * It does not redirect based on profile/role/permission. Doing permission
 * redirects here can create self-redirect loops (for example /dashboard ->
 * /dashboard when the permission RPC returns false). The database RLS and the
 * protected application shell remain the authorization boundaries.
 */
export async function middleware(request: NextRequest) {
  const pathname = request.nextUrl.pathname;

  // The login page and static assets are public. No finance UI is rendered by
  // the login route itself; it is an isolated Account surface.
  if (pathname === "/login") {
    return NextResponse.next();
  }

  const response = NextResponse.next({
    request: { headers: request.headers },
  });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookies) {
          cookies.forEach(({ name, value, options }) => {
            response.cookies.set(name, value, options);
          });
        },
      },
    }
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    const loginUrl = request.nextUrl.clone();
    loginUrl.pathname = "/login";
    loginUrl.search = "";
    const redirect = NextResponse.redirect(loginUrl);
    // Preserve any Supabase session-refresh cookies generated by getUser().
    response.cookies.getAll().forEach((cookie) => redirect.cookies.set(cookie));
    return redirect;
  }

  // Authentication is valid. Authorization is evaluated by AppShell and,
  // critically, by Supabase RLS policies for every database operation.
  return response;
}

export const config = {
  matcher: ["/((?!_next/static|_next/image|favicon.ico).*)"],
};
